return {}
-- return {
--     'echasnovski/mini.completion',
--     version = false,
--     config = function()
--         require('mini.completion').setup({
--             -- Module mappings. Use `''` (empty string) to disable one. Some of them
--             -- might conflict with system mappings.
--             mappings = {
--                 force_twostep = '', -- Force two-step completion
--                 force_fallback = '<A-Space>', -- Force fallback completion
--             },
--         })
--     end
-- }